import EncounterEvolution, { encounterStatus } from './EncounterEvolution';
import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from 'react';
import { api } from '../services/api';
import { ROLE_LABELS, type Center, type ClinicalState, type Encounter, type Membership, type WoundEpisode } from '../types';
import { formatDate, formatDateTime, formatRut, validateRut } from '../utils';
import { canUploadClinicalDocuments, canViewCommittee, hasRole, isReferralProfile, PRIMARY_CARE_ROLES } from '../permissions';
import EncounterWorkspace from './EncounterWorkspace';
import PreAdmissionCard from './PreAdmissionCard';
import CommitteeView from './CommitteeView';
import SpecialistCaseSummary from './SpecialistCaseSummary';
import { CoordinationPatientView, SocialPatientView } from './RolePatientViews';
import './clinical-dashboard.css';

// Local aliases keep the clinical screen compact and make mobile navigation explicit.
type Props = { center: Center; membership: Membership; state: ClinicalState | null; onRefresh: () => Promise<void>; onEncounterChanged: (encounter: Encounter) => void; demoMode?: boolean };

export default function ClinicalDashboard({ center, membership, state, onRefresh, onEncounterChanged, demoMode = false }: Props) {
  const [patientId, setPatientId] = useState(''); const [episodeId, setEpisodeId] = useState(''); const [encounterId, setEncounterId] = useState(''); const [query, setQuery] = useState(''); const [message, setMessage] = useState('');
  const [committee, setCommittee] = useState(false);
  const [workspace, setWorkspace] = useState<'care' | 'referral' | 'social' | 'coordination'>(() => hasRole(membership, PRIMARY_CARE_ROLES) ? 'care' : hasRole(membership, ['general_surgeon', 'vascular_surgeon', 'vascular_nurse', 'traumatologist', 'physiatrist']) ? 'referral' : membership.roles.includes('social_worker') ? 'social' : 'coordination');
  const [patientBrowserOpen, setPatientBrowserOpen] = useState(true);
  useEffect(() => {
    if (!demoMode || !state?.patients.length) return;
    const firstPatient = state.patients[0];
    const firstEpisode = state.episodes.find((item) => item.patientId === firstPatient.id);
    setPatientId(firstPatient.id); setEpisodeId(firstEpisode?.id || ''); setPatientBrowserOpen(false);
  }, [demoMode, state]);
  const patients = useMemo(() => (state?.patients || []).filter((item) => !['referral', 'social'].includes(workspace) || state?.tasks.some((task) => task.patientId === item.id && membership.roles.includes(task.recipientRole))).filter((item) => `${item.name} ${item.rut}`.toLowerCase().includes(query.toLowerCase())), [state, query, workspace, membership.roles]);
  const patient = state?.patients.find((item) => item.id === patientId); const episodes = state?.episodes.filter((item) => item.patientId === patientId) || []; const episode = state?.episodes.find((item) => item.id === episodeId); const encounters = state?.encounters.filter((item) => item.episodeId === episodeId).sort((a, b) => b.encounterDate.localeCompare(a.encounterDate)) || []; const encounter = state?.encounters.find((item) => item.id === encounterId);
  const canCreatePatient = hasRole(membership, ['coordinator', 'tens', 'nurse', 'doctor']);
  const canOpenEpisode = hasRole(membership, ['coordinator', 'tens', 'nurse', 'doctor']);
  const canStartEncounter = hasRole(membership, ['tens', 'nurse', 'doctor']);
  const referralView = workspace === 'referral'; const socialView = workspace === 'social'; const coordinationView = workspace === 'coordination'; const tensOnly = membership.roles.includes('tens') && !hasRole(membership, ['nurse', 'doctor']);
  const createPatient = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (demoMode) return; const form = event.currentTarget; const data = new FormData(form); const rut = String(data.get('rut')); if (!validateRut(rut)) { setMessage('Revisa el RUT ingresado.'); return; } try { const result = await api.createPatient(center.id, { name: String(data.get('name')), rut }); form.reset(); await onRefresh(); setPatientId(result.patient.id); setPatientBrowserOpen(false); setMessage('Paciente creado. Ahora registra el episodio.'); } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'No fue posible crear el paciente.'); } };
  const createEpisode = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (demoMode) return; const form = event.currentTarget; const data = new FormData(form); try { const result = await api.createEpisode(center.id, { patientId, side: data.get('side') as 'right' | 'left', location: String(data.get('location')), priority: data.get('priority') as WoundEpisode['priority'], consentForPhotography: data.get('consent') === 'on' }); form.reset(); await onRefresh(); setEpisodeId(result.episode.id); setMessage('Episodio abierto.'); } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'No fue posible abrir el episodio.'); } };
  const createEncounter = async () => { if (demoMode || !patient || !episode) return; try { const result = await api.createEncounter(center.id, { patientId: patient.id, episodeId: episode.id, encounterDate: new Date().toISOString() }); await onRefresh(); setEncounterId(result.encounter.id); } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'No fue posible iniciar la atención.'); } };
  const uploadAttachment = async (event: ChangeEvent<HTMLInputElement>) => { if (demoMode) return; const file = event.target.files?.[0]; if (!file || !episode) return; if (file.size > 10 * 1024 * 1024) { setMessage('El archivo supera 10 MB.'); return; } const reader = new FileReader(); reader.onload = async () => { try { await api.uploadAttachment(center.id, episode.id, { dataUrl: String(reader.result), kind: (event.target.dataset.kind || 'other') as 'laboratory' | 'pvr' | 'imaging' | 'other', title: file.name }); await onRefresh(); setMessage('Documento clínico cargado de forma privada.'); } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'No fue posible cargar el documento.'); } }; reader.readAsDataURL(file); };

  if (!state) return <div className="centered compact"><div className="spinner" /><p>Cargando pacientes y tareas…</p></div>;
  if (committee && patient && episode) return <CommitteeView patient={patient} episode={episode} encounters={encounters} tasks={state.tasks.filter((item) => item.episodeId === episode.id)} attachments={state.attachments.filter((item) => item.episodeId === episode.id)} onBack={() => setCommittee(false)} />;
  if (encounter && patient && episode) return <EncounterWorkspace center={center} membership={membership} patient={patient} episode={episode} encounter={encounter} tasks={state.tasks.filter((item) => item.episodeId === episode.id)} onBack={() => setEncounterId('')} onChanged={(value) => { onEncounterChanged(value); }} onRefresh={onRefresh} demoMode={demoMode} />;

  const relevantTasks = state.tasks.filter((task) => membership.roles.includes('coordinator') || membership.roles.includes(task.recipientRole) || task.createdByUid === membership.uid).filter((task) => task.status !== 'resolved');
  return <section>
    <label className="workspace-selector">Espacio de trabajo<select value={workspace} onChange={(e) => { setWorkspace(e.target.value as typeof workspace); setEncounterId(''); setPatientId(''); setEpisodeId(''); setPatientBrowserOpen(true); }}>{hasRole(membership, PRIMARY_CARE_ROLES) && <option value="care">Atención del equipo</option>}{hasRole(membership, ['general_surgeon', 'vascular_surgeon', 'vascular_nurse', 'traumatologist', 'physiatrist']) && <option value="referral">Casos derivados</option>}{membership.roles.includes('social_worker') && <option value="social">Trabajo social</option>}{membership.roles.includes('coordinator') && <option value="coordination">Coordinación</option>}</select></label>
    <div className="section-heading"><div><p className="eyebrow">{center.name}</p><h1>Panel de atención</h1><p>{membership.roles.map((role) => ROLE_LABELS[role]).join(' · ')}</p></div><span className="metric urgent-metric">{relevantTasks.length} gestiones activas</span></div>
    {message && <div className="notice">{message}<button onClick={() => setMessage('')}>×</button></div>}
    <div className={`clinical-grid ${patientBrowserOpen ? '' : 'patient-browser-collapsed'}`}>
      {patientBrowserOpen ? <aside className="panel patient-browser"><div className="patient-browser-heading"><h2>Pacientes</h2><button type="button" className="patient-browser-collapse" onClick={() => setPatientBrowserOpen(false)} aria-label="Plegar buscador de pacientes" title="Plegar buscador">‹</button></div><input type="search" placeholder="Buscar por nombre o RUT" value={query} onChange={(event) => setQuery(event.target.value)} />
        <div className="stack scroll-list">{patients.map((item) => <button className={`patient-row ${patientId === item.id ? 'selected' : ''}`} key={item.id} onClick={() => { setPatientId(item.id); setEpisodeId(''); setPatientBrowserOpen(false); }}><strong>{item.name}</strong><small>{formatRut(item.rut)} · Preingreso {item.preAdmissionStatus === 'validated' ? 'validado' : 'pendiente'}</small></button>)}{patients.length === 0 && <p className="muted">No hay pacientes coincidentes.</p>}</div>
        {canCreatePatient && <details><summary>+ Ingreso rápido</summary><form className="mini-form" onSubmit={createPatient}><label>Nombre completo<input name="name" required /></label><label>RUT<input name="rut" placeholder="12.345.678-5" required /></label><button className="primary">Crear paciente</button></form></details>}
      </aside> : <button type="button" className="patient-browser-launcher" onClick={() => setPatientBrowserOpen(true)} aria-expanded="false" aria-label="Abrir buscador de pacientes"><span className="patient-browser-launcher-icon" aria-hidden="true">⌕</span><span>Pacientes</span></button>}
      <div className="workspace-column">
        {!patient && <div className="panel empty-state"><h2>{referralView || socialView ? 'Selecciona un caso derivado' : 'Selecciona un paciente'}</h2><p>{referralView || socialView ? 'Sólo aparecen casos con una gestión asignada a tu perfil.' : 'En móvil puedes crear un ingreso mínimo con nombre y RUT; TENS prepara los antecedentes y enfermería o medicina los valida.'}</p></div>}
        {patient && <>
          {hasRole(membership, ['tens', 'nurse', 'doctor']) && workspace === 'care' && <details className="panel"><summary>Identificación y antecedentes · {patient.name}</summary><PreAdmissionCard key={patient.id} centerId={center.id} membership={membership} patient={patient} onSaved={onRefresh} demoMode={demoMode} /></details>}
          {socialView && <SocialPatientView key={patient.id} centerId={center.id} patient={patient} onSaved={onRefresh} demoMode={demoMode} />}
          {(coordinationView || (tensOnly && workspace === 'care')) && <CoordinationPatientView key={patient.id} centerId={center.id} patient={patient} onSaved={onRefresh} canAssignTens={hasRole(membership, ['coordinator', 'nurse', 'doctor'])} demoMode={demoMode} />}
          <div className="panel">
          <h3>Episodios de herida</h3><div className="stack">{episodes.map((item) => <button className={`episode-row ${episodeId === item.id ? 'selected' : ''}`} key={item.id} onClick={() => setEpisodeId(item.id)}><span><strong>{item.location}</strong><small>Pie {item.side === 'right' ? 'derecho' : 'izquierdo'} · inicio {formatDate(item.createdAt)}</small></span><span className={`pill ${item.priority}`}>{item.priority === 'urgent' ? 'Urgente' : item.priority === 'soon' ? 'Pronto' : 'Habitual'}</span></button>)}</div>
          {canOpenEpisode && <details><summary>+ Abrir episodio</summary><form className="mini-form horizontal" onSubmit={createEpisode}><label>Lado<select name="side"><option value="right">Derecho</option><option value="left">Izquierdo</option></select></label><label>Ubicación<input name="location" required placeholder="Plantar, hallux…" /></label><label>Prioridad<select name="priority"><option value="routine">Habitual</option><option value="soon">Pronto</option><option value="urgent">Urgente</option></select></label><label className="check"><input type="checkbox" name="consent" /> Consentimiento fotográfico registrado</label><button className="primary">Abrir episodio</button></form></details>}
          </div>
        </>}
        {episode && referralView && patient && <SpecialistCaseSummary centerId={center.id} membership={membership} patient={patient} episode={episode} encounters={encounters} tasks={state.tasks.filter((item) => item.episodeId === episode.id)} attachments={state.attachments.filter((item) => item.episodeId === episode.id)} onRefresh={onRefresh} onResolved={() => { setPatientId(''); setEpisodeId(''); setPatientBrowserOpen(true); setMessage('Respuesta registrada. La gestión quedó resuelta y el caso salió de tus derivados.'); }} demoMode={demoMode} />}
        {episode && !referralView && !socialView && !coordinationView && <details className="panel"><summary>{tensOnly ? 'Comparar fotografías entre fechas' : 'Evolución y respuestas de especialidades'}</summary><EncounterEvolution encounters={encounters} tasks={state.tasks.filter((item) => item.episodeId === episode.id)} photosOnly={tensOnly} /></details>}

        {episode && !referralView && !socialView && !coordinationView && <div className="panel"><div className="card-heading"><div><p className="eyebrow">{tensOnly ? 'Registro fotográfico' : 'Atenciones compartidas'}</p><h2>{episode.location}</h2></div><div className="top-actions">{canViewCommittee(membership) && <button className="ghost" onClick={() => setCommittee(true)}>Presentación de comité</button>}{canStartEncounter && <button className="primary" onClick={() => void createEncounter()}>{tensOnly ? 'Iniciar registro fotográfico' : 'Nueva atención'}</button>}</div></div><div className="stack">{encounters.map((item) => <button className="encounter-row" key={item.id} onClick={() => setEncounterId(item.id)}><span><strong>{formatDateTime(item.encounterDate)}</strong><small>Versión {item.version} · {item.photos.length} fotos</small></span><span className={`pill ${item.status}`}>{encounterStatus(item.status)}</span></button>)}{encounters.length === 0 && <p className="muted">Aún no hay registros para este episodio.</p>}</div>{canUploadClinicalDocuments(membership) && <><div className="attachment-actions"><label className="ghost">Subir laboratorio<input hidden type="file" accept="application/pdf,image/*" data-kind="laboratory" onChange={(event) => void uploadAttachment(event)} /></label><label className="ghost">Subir PVR<input hidden type="file" accept="application/pdf,image/*" data-kind="pvr" onChange={(event) => void uploadAttachment(event)} /></label></div>{state.attachments.filter((item) => item.episodeId === episode.id).map((item) => item.url ? <a className="document-link" key={item.id} href={item.url} target="_blank" rel="noreferrer">📎 {item.title}</a> : <div className="document-link" key={item.id}>📎 {item.title}</div>)}</>}</div>}
        {!referralView && !tensOnly && relevantTasks.length > 0 && <div className="panel"><h2>Gestiones para mi perfil</h2><div className="stack">{relevantTasks.map((task) => <article className="task-card" key={task.id}><div><strong>{task.title}</strong><small>{task.reason}</small></div><span className={`pill ${task.priority}`}>{task.priority}</span></article>)}</div></div>}
      </div>
    </div>
  </section>;
}
