import { FormEvent, useState } from 'react';
import { api } from '../services/api';
import type { Membership, Patient } from '../types';

const join = (values: string[]) => values.join(', ');
const list = (value: FormDataEntryValue | null) => String(value || '').split(',').map((item) => item.trim()).filter(Boolean);

export default function PreAdmissionCard({ centerId, membership, patient, onSaved }: { centerId: string; membership: Membership; patient: Patient; onSaved: () => Promise<void> }) {
  const [message, setMessage] = useState(''); const canEdit = membership.roles.some((role) => ['nurse', 'doctor', 'social_worker', 'physiatrist', 'coordinator'].includes(role));
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); try { await api.updatePatient(centerId, patient.id, { birthDate: String(data.get('birthDate')), contact: String(data.get('contact')), comuna: String(data.get('comuna')), preAdmissionStatus: data.get('confirmed') === 'on' ? 'validated' : 'in_progress', anamnesis: { diabetesTreatment: String(data.get('diabetesTreatment')), medicalHistory: list(data.get('medicalHistory')), surgicalHistory: list(data.get('surgicalHistory')), allergies: list(data.get('allergies')), medications: list(data.get('medications')), smoking: String(data.get('smoking')), renalDisease: String(data.get('renalDisease')), vascularHistory: String(data.get('vascularHistory')), neuropathy: String(data.get('neuropathy')), previousAmputations: String(data.get('previousAmputations')) }, social: { supportNetwork: String(data.get('supportNetwork')), mobility: String(data.get('mobility')), transportBarriers: String(data.get('transportBarriers')), housingBarriers: String(data.get('housingBarriers')), notes: String(data.get('socialNotes')) }, verification: { status: data.get('confirmed') === 'on' ? 'confirmed' : 'draft' } }); await onSaved(); setMessage('Preingreso guardado.'); } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'No fue posible guardar.'); } };
  return <details className="preadmission"><summary>Preingreso clínico y social</summary><form className="form-grid" onSubmit={save}><fieldset disabled={!canEdit} className="form-grid full"><label>Fecha de nacimiento<input type="date" name="birthDate" defaultValue={patient.birthDate} /></label><label>Contacto<input name="contact" defaultValue={patient.contact} /></label><label>Comuna<input name="comuna" defaultValue={patient.comuna} /></label><label>Tratamiento diabetes<input name="diabetesTreatment" defaultValue={patient.anamnesis.diabetesTreatment} /></label><label>Antecedentes médicos<input name="medicalHistory" defaultValue={join(patient.anamnesis.medicalHistory)} /></label><label>Antecedentes quirúrgicos<input name="surgicalHistory" defaultValue={join(patient.anamnesis.surgicalHistory)} /></label><label>Alergias<input name="allergies" defaultValue={join(patient.anamnesis.allergies)} /></label><label>Fármacos<input name="medications" defaultValue={join(patient.anamnesis.medications)} /></label><label>Tabaquismo<input name="smoking" defaultValue={patient.anamnesis.smoking} /></label><label>Enfermedad renal<input name="renalDisease" defaultValue={patient.anamnesis.renalDisease} /></label><label>Antecedente vascular<input name="vascularHistory" defaultValue={patient.anamnesis.vascularHistory} /></label><label>Neuropatía<input name="neuropathy" defaultValue={patient.anamnesis.neuropathy} /></label><label>Amputaciones previas<input name="previousAmputations" defaultValue={patient.anamnesis.previousAmputations} /></label><label>Red de apoyo<input name="supportNetwork" defaultValue={patient.social.supportNetwork} /></label><label>Movilidad<input name="mobility" defaultValue={patient.social.mobility} /></label><label>Barreras de transporte<input name="transportBarriers" defaultValue={patient.social.transportBarriers} /></label><label>Barreras de vivienda<input name="housingBarriers" defaultValue={patient.social.housingBarriers} /></label><label>Observaciones sociales<input name="socialNotes" defaultValue={patient.social.notes} /></label><label className="check full"><input type="checkbox" name="confirmed" defaultChecked={patient.preAdmissionStatus === 'validated'} /> Confirmo que revisé los antecedentes</label></fieldset>{canEdit && <button className="primary full">Guardar preingreso</button>}{message && <p className="helper full">{message}</p>}</form></details>;
}
